### ISSUE TITLE
 got issue in send-inscription.test.ts

### ISSUE THREAD

**Issue by cloud6605** [unisat-wallet/dev-support#29]
I'm checking unisat-wallet-sdk, especially  send-inscription.test.ts.
It is working well.
But I just changed the fromBtcWallet & fromAssetWallet address Type.
Then I have issue, could you check what is wrong?

send one inscription with lower outputValue:
     Error: Input #1 has too much or too little data to clean
      at Object.inputCheckUncleanFinalized (node_modules\bip174\src\lib\utils.js:51:11)
      at Psbt.clearFinalizedInput (node_modules\bip174\src\lib\psbt.js:120:13)
      at Psbt._finalizeTaprootInput (node_modules\bitcoinjs-lib\src\psbt.js:356:15)
      at Psbt.finalizeInput (node_modules\bitcoinjs-lib\src\psbt.js:281:19)
      at C:\Users\Administrator\Downloads\wallet-sdk\src\wallet\estimate-wallet.ts:176:14
      at Array.forEach (<anonymous>)
      at EstimateWallet.<anonymous> (src\wallet\estimate-wallet.ts:174:15)
      at Generator.next (<anonymous>)
      at fulfilled (src\wallet\estimate-wallet.ts:5:58)

**Comment by cloud6605** [comment]
Yes, but in this test,  fromBTCWallet and fromAssetWallet  addressType is always same.
But if 2 wallet addresstypes are different, then unisat-sdk script has issue.
Especially,  fromBTCWallet(P2SH_P2WKH) and fromAssetWallet(P2TR).
Can you please check in this case?

**Comment by cloud6605** [comment]
![image](https://github.com/unisat-wallet/dev-support/assets/132422140/26834d49-4b75-445f-8092-a532d19c56da)

**Comment by ponypick** [comment]
The send-inscription.ts doesn't work for me and shows the same error, when the wallet sign psbt:
![image](https://github.com/user-attachments/assets/10f8e868-e51d-4fe9-8bef-a3396d2b2c27)

Here is the code when the error occur:
 await wallet.signPsbt(psbt, {
      autoFinalized: true,
      toSignInputs,
    });
