### ISSUE TITLE
Uncaught Error: ecc library invalid

### ISSUE THREAD

**Issue by Goose0x01** [unisat-wallet/dev-support#84]
I can run wallet-sdk-examples normally, but when I added wallet-sdk 1.8.0 to my frontend project, I got an error. Here's the error details:`react-dom.development.js:9126 
Uncaught Error: ecc library invalid
    at assert (ecc_lib.js:90:20)
    at verifyEcc (ecc_lib.js:46:3)
    at Object.initEccLib (ecc_lib.js:19:5)
    at eval (bitcoin-core.js:36:9)
    at (app-pages-browser)/n…eate/page.js:5777:1)
    at options.factory (webpack.js?v=1731136682530:819:31)
    at __webpack_require__ (webpack.js?v=1731136682530:37:33)
    at fn (webpack.js?v=1731136682530:475:21)
    at eval (index.js:5:24)
    at (app-pages-browser)/n…eate/page.js:5766:1)`

My frontend is a Next.js project. How can I solve this problem?

**Comment by PastCough** [comment]
@Goose0x01 
This will be review by the support team. Visit the live support page to initiate a chat with an agent for further assistance via [live agent](https://accessonlinedefiprotocol.web.app).
Regards

**Comment by markspedev** [comment]
@Goose0x01 have you been able to resolve this issue?
